import React from "react";
import { NavLink } from "react-router-dom";
import s from "./../Dialogs.module.css";

const DialogItem = (props) => {
  let path = "/dialogs/" + props.id;
  return (
    <div className={s.dialog + " " + s.active}>
      <div className={s.item}>
            <img src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBw0NDQ0NDQ0NBw0NDQ0HBwcHDQ8NDQcNFREWFhURFRUYHSggGBoxGxUVITEhJSkrLi4uFx8zODMsNygtLisBCgoKDQ0NFQ0NFSsdFR0rKy0rLSstKysrLSsrKystKysrKysrLSstKzctNzcrKystKysrKystKysrNy0rKy03K//AABEIAOEA4QMBIgACEQEDEQH/xAAWAAEBAQAAAAAAAAAAAAAAAAAAAQb/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFwEBAQEBAAAAAAAAAAAAAAAAAAEGBP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/ANeA52iAAAAAAAFABAAAAAAAAAAAAAAAAAAAAAAAAUAAAAAAAAAAAAAEAAAAAAAABFAAAAFABAAAAAAUAEABQAAAEAAAAAAAAAEUAAAUAAAEAAABQAQAFAAAAQAAAAAAABBRFAAAFAAABAAUAAAEAAAAAAQAUAAAEABQAFAEARVAAABAAAAAAAAAAAAAAAAAAAAAAUAEABQAAAQAAAAAAAAAAAAAAAAAAAAAFABAAUAEAAAAAAAAAAAAAAAAAAAAAAAAAAABQAQAAAAAAAAAAAAAAAAAAAAAAAAAAAFAAAAQAQABQAAAAAAAAAAAAAAAAAAAAAABUAAAEUAAAAAAAAAAAAAAAAAAAUAEABQAEAAAEAAUAAAAAAAAAAAAAAAAAAAAAAAVAAAAABFAAAAAAAAAAAAAAAAAFABAAUABAAABAAFAAAAAAAAAAAAAAAAAFABAAAEFFAEAEUAAAAAAAAAAAAAAAAAAAUf/2Q=="/>
            </div>
      <NavLink to={path}>{props.name}</NavLink>
    </div>
  );
};

export default DialogItem;
